#use_frameworks!

source "https://github.com/CocoaPods/Specs.git"
source "https://github.com/rRun/xy_podSepcs.git"

target 'XYShareSdk_Example' do
  pod 'XYShareSdk', :path => '../'

  target 'XYShareSdk_Tests' do
    inherit! :search_paths

    
  end
end
